# Generated by Django 5.0.1 on 2025-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
